workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        FIREBASE_URL: "https://novaticker-default-rtdb.firebaseio.com/"
    scripts:
      - echo "🔧 APK 빌드 준비 중입니다."
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
