workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.example.novaticker"
      android_signing:
        - keystore_reference
      groups:
        - android_credentials
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
